- .gitignore
- README.md
add .gitignore, some folders and readme
> Basic stuff

- .github/workflows/backend-ci.yml
This CI (Continuous Integration) pipeline definition file is designed to perform a series of related continuous integration tasks on the backend of the application. Here's what each part of the pipeline does:
**Workflow Name:** The name of the workflow is "CI Backend". This is just a friendly name that identifies the purpose of the workflow.
**Workflow Triggers:** The workflow is triggered when a pull request is created in the develop branch. This means that this workflow will be executed automatically when changes are proposed to the "develop" branch.
**Filtering changes by path:** The workflow will only be triggered if the changes are made within the 'backend/' directory in the repository. This ensures that CI actions are executed only when code related to the backend of the application …
> [DEVOPS] Adding CI pipeline for Backend

- .github/workflows/frontend_ci.yaml
This Pull Request resolve the Devops Issue #9 
This code is a workflow definition to use with GitHub Actions, which is an automation tool provided by GitHub for automatically performing actions in response to specific events in the GitHub repository. The "Frontend CI" workflow will be triggered when a "push" event occurs on the "main" branch of  the repository.
1. **Checkout code**: This step clones the source code from the repository into the GitHub Actions virtual machine.
2. **Install Node.js and npm**: In this step, Node.js and npm are installed on the virtual machine. Version 16 of Node.js is used.
3. **Install dependencies**: Here, the npm install command is executed to install project dependencies.
4. **Build app**: This step runs the npm run build command to compile the React …
> [DEVOPS] Add pipeline CI for frontend

- .github/workflows/mobile_ci.yaml
The workflow setup process for mobile devices is as follows:
**1. Checkout Code:** This step uses the GitHub action `actions/checkout@v2` to fetch the source code from the repository.
**2. Set Up Kotlin Environment:** This step sets up the environment to use Java 11 using the `actions/setup-java@v2` action. You can configure it with the version you are using of your project.
**3. Build the Application:** It runs the `./gradlew build` command to compile your Kotlin application. This step compiles the project's source code.
**4. Run Test:** It executes the `./gradlew` test command to run unit tests for the application. This verifies the code functions correctly.
**5. Package the Application:** The `./gradlew assembleRelease` command is run to package the application. This may include …
> [DEVOPS #18] Add CI pipeline for mobile

- .github/workflows/data_ci.yaml
This GitHub Actions YAML file named "CI Data" defines a workflow that is triggered when a pull request is made to the "main" branch and when changes are detected in files located in the "data" directory. The workflow has several key components.
The job named "ci" that runs on the "ubuntu-latest" environment. This job includes several steps:
1. "Checkout code": It checks out the repository code using the "actions/checkout@v2" action.
2. "Set up Python 3.11": It sets up Python 3.11 using the "actions/setup-python@v2" action, allowing the workflow to use the required Python version.
3. "Check Requirements file existence": It checks if the "data/requirements.txt" file exists using a custom action "thebinaryfelix/check-file-existence-action@1.0.0" and stores the result in an output variable. …
> [DEVOPS #10] Add CI pipeline for data

- .github/workflows/frontend_ci.yaml
> Devops fix frontend pipeline

- .github/workflows/mobile_ci.yaml
> [DEVOPS] fix mobile ci

- frontend/src/app/Enrollment.tsx
- frontend/src/app/auth/login/page.tsx
- frontend/src/components/index.tsx
- frontend/src/components/organisms/CardAuth.tsx
create organism component by enrollment template
> Fe feat (card auth) : orgnism component

- frontend/src/components/atoms/InputCode/inputCode.tsx
- frontend/src/components/index.tsx
- frontend/src/components/molecules/VerificationCode/verificationCode.tsx
I added the atom input Code and the molecule verification Code, both reusable components, to the code verification page.
> Fe feat [moelucles] : verification code

- frontend/src/components/atoms/Button/button.tsx
- frontend/src/components/atoms/Button/index.scss
fix scss button in atom component ,
fix in page login
> FE fix(button): style scss

- frontend/.gitignore
- frontend/resources/styles/variables.scss
- frontend/src/app/auth/auth.tsx
- frontend/src/components/atoms/Button/button.tsx
- frontend/src/components/atoms/Button/index.scss
Color for disabled style created.
Style for disabled button created.
> [FE] style add style disabled button

- .github/workflows/mobile_ci.yaml
adding Java distribution called "AdoptOpenJDK"
> [DEVOPS] Fix mobile pipeline

- frontend/.babelrc
- frontend/jest.config.js
- frontend/package.json
- frontend/src/test/sample.test.js
- frontend/src/test/validation.test.tsx
- frontend/src/utilities/Constant.tsx
- frontend/src/utilities/Contant.tsx
- frontend/src/utilities/Validation.tsx
> feat(test):jest

- frontend/src/test/validation.test.tsx
- frontend/src/utilities/Constant.tsx
- frontend/src/utilities/Validation.tsx
I added validation for the mail entry, following the same logic that was used to validate the name entry. In this case they differ in the pattern for the email = '/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/'
> Fe add validation email

- QA/contracts/contract_registration.json
[QA] :
The contract for registration has been created in JSON format. References: #54 , @PaulaRV01
> [QA] Define a contract for registration

- QA/contracts/contract_profile_import.json
creation of json contract for profile import
> [QA] profile import json contract

- frontend/src/test/validation.test.tsx
- frontend/src/utilities/Constant.tsx
- frontend/src/utilities/Validation.tsx
> add validate password test

- QA/contracts/contract_create_profile.json
[QA] :
The contract for profile creation has been created in JSON format. 
References: #54 , @luzelenatt
> [QA] Define a contract for profile creation

- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/Tag/index.scss
- frontend/src/components/atoms/Tag/tag.tsx
- frontend/src/components/index.tsx
create tag component with properties: icon, text, isActive, path
> Feat(component):tag component

- data/sentiment_analysis/Testing/sa_lstm_pytorch.ipynb
It makes use of LSTM for its implementation.
References: #112 , @vladnn100
> [DATA] feat: Add sentiment analysis with Pytorch

- frontend/package.json
- frontend/src/app/auth/login/constant.tsx
- frontend/src/app/auth/login/page.tsx
- frontend/src/components/atoms/Button/button.tsx
- frontend/src/components/atoms/Input/input.tsx
- INSTALL yup
- install formik
- validate regex 
- sendForm
> Fe feat (validate) login

- backend/internal/comment/application/commentUseCase.go
- backend/internal/comment/domain/comment.go
- backend/internal/comment/infrastructure/commentHandler.go
- backend/internal/comment/infrastructure/commentRepository.go
- backend/internal/comment/router.go
- backend/internal/router.go
The initial functionality of comments and their basic operations have been implemented, as well as an improvement in route management.
> [BE] Add initial functionality to comments 

- frontend/src/app/auth/login/page.tsx
- frontend/src/app/auth/register/page.tsx
I added the component that redirects from login to registration and from registration to login.
I resolved issue 310.
> FE fix [ page register ] : connect page

- frontend/resources/styles/variables.scss
- frontend/src/app/test/page.tsx
- frontend/src/components/index.tsx
- frontend/src/components/molecules/AvatarInput/index.scss
- frontend/src/components/molecules/AvatarInput/index.tsx
> [Fe] featture(molecule) : avatar_input

- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/Input/input.tsx
This time, I put pass option in input, I mean, now there's the password type so when someone puts "password" as a type in a input, this input will has the hide and see option the password.
> [FE] featture(Component): PasswordInput

- android/app/src/main/java/com/social/presentation/authentication/RegisterFragment.kt
- android/app/src/main/res/layout/fragment_register.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/values/themes.xml
RegisterFragment has been changed to give a message to the user for the next features like login with Google and Mastodon credentials
Fragment_register: this fragment has been modified according to the new design
New labels was added to "strings.xml" resource too
Mastodon text in some phones has been fixed in "themes.xml" resource
> [M] update _register_screen

- android/app/src/main/java/com/social/data/repository/SocialAppRepositoryImp.kt
- android/app/src/main/java/com/social/data/source/remote/ApiInterface.kt
- android/app/src/main/java/com/social/data/source/remote/dto/LoginDto.kt
- android/app/src/main/java/com/social/di/ApiSocialApp.kt
- android/app/src/main/java/com/social/domain/SocialAppRepository.kt
- android/app/src/main/java/com/social/domain/imp.kt
- android/app/src/main/java/com/social/domain/model/Login.kt
- android/app/src/main/java/com/social/domain/model/LoginBody.kt
- android/app/src/main/java/com/social/domain/model/LoginUserData.kt
- android/app/src/main/java/com/social/domain/use_case/ValidateUser.kt
- android/app/src/main/java/com/social/utils/Resource.kt
According to Clean Architecture the core of the project are the entities:
First of all in an object I defined the API to connect from the backend using Retrofil and OkHttpClient class. Using the base url of the API, the client and the JSON format we can build our function to connect to backend using the interface:
So, for Login, I defined a data class for the body of the endpoint request, in this case for the Login we defined 'username' and 'password' attributes of the body:
In adittion we wait a response and status from server:
Once the data that the application will send in the body of the json and the response that we are going to receive are completed, we proceed to integrate both functionalities into a suspend function in an interface that we will later implement:
Now, we can design …
> [M] Login endpoint integration

- android/app/src/main/java/com/social/domain/model/ChatMessageUser.kt
- android/app/src/main/java/com/social/presentation/interaction/chats/ChatAdapter.kt
- android/app/src/main/java/com/social/presentation/interaction/chats/ChatScreenFragment.kt
- android/app/src/main/res/drawable/background_received_message.xml
- android/app/src/main/res/drawable/background_send_message.xml
- android/app/src/main/res/drawable/icon_arrow_back.xml
- android/app/src/main/res/drawable/icon_camera.xml
- android/app/src/main/res/drawable/icon_face.xml
- android/app/src/main/res/drawable/icon_microphone.xml
- android/app/src/main/res/drawable/icon_phone.xml
- android/app/src/main/res/drawable/icon_send_message.xml
- android/app/src/main/res/drawable/icon_video_camera.xml
- android/app/src/main/res/layout/container_received_message.xml
- android/app/src/main/res/layout/container_send_message.xml
- android/app/src/main/res/layout/fragment_chat_screen.xml
- android/app/src/main/res/navigation/navigation.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/values/themes.xml
In this section, the frontend of the chat screen that shows the conversation messages has been developed. This task is divided into three files. Firstly, we have 'ChatMessageUser' located in 'domain/model', which is used to represent the data related to a user in a chat using a data structure. The following two files are located in 'presentation/interaction/chats'. The first, called 'ChatScreenFragment', is intended for the backend team to deploy their code. The second, 'ChatAdapter', is used to display each sent message in a list view, making use of the data structure provided by 'ChatMessageUser'.
> [M] chat screen

- android/app/src/main/java/com/social/presentation/authentication/LoginDataState.kt
- android/app/src/main/java/com/social/presentation/authentication/LoginEvent.kt
- android/app/src/main/java/com/social/presentation/authentication/LoginViewModel.kt
- android/app/src/main/java/com/social/presentation/authentication/TextState.kt
1. **Summary**
Added special classes to manage states for the UI. These classes interact with viewmodel class to detect user events in the UI
2. **Implementation**
- LoginDataState: Three states to control the UI
- Login Event and TextState: Class to detect the states of controls
- ViewModel: Here we manage the states and communication with  Login Use Case and evaluate controls states
> [M] State events and Viewmodel Login added

- frontend/src/app/auth/login/page.tsx
Fix change by label in login , because tag has an email label and they wabnt to also use username or email
> fix (label) : change email by email or user

- android/app/build.gradle.kts
- android/app/src/androidTest/java/com/social/interactionTest/chatsTest/ChatAdapterTest.kt
- android/app/src/androidTest/java/com/social/interactionTest/chatsTest/ChatMessageUserTest.kt
- android/app/src/main/java/com/social/presentation/interaction/chats/ChatAdapter.kt
Tested for ChatAdapter and ChatMessageData. Below I show the results obtained:
> [M] junit test chat screen

- android/app/src/androidTest/java/com/social/utilsTest/CodeGeneratorTest.kt
- android/app/src/androidTest/java/com/social/utilsTest/ValidationTest.kt
- android/app/src/main/java/com/social/utils/Validation.kt
> [M] test validaciones generatecode

- QA/postman_test/QA_postman_test_login_061023.json
[QA] :
The postman test for login in JSON format.
References: #321
> [QA] postman test login 061023

- QA/postman_test/QA_postman_test_Register_061023.json
The postman test for REGISTER in JSON format.
> [QA] postman test Register 061023 

- backend/internal/comment/application/commentUseCase.go
- backend/internal/comment/infrastructure/commentHandler.go
- backend/internal/comment/infrastructure/commentHandler_test.go
- backend/internal/comment/infrastructure/commentRepository.go
- backend/internal/comment/router.go
Testing has been implemented for comment use cases. 
Some functions related to data handling have also been corrected and some code blocks have been refactored.
> [BE] feat: Implement testing for comment endpoints

- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/Button/button.tsx
- frontend/src/components/atoms/Button/index.scss
I did changes on styles of button
> FE_Feat_StylesButton

- frontend/next.config.js
- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/Button/index.scss
- frontend/src/components/index.tsx
fix components && include iconSPam in list also , redirection permanent in false
> fix ( component ) : new component in list components

- QA/contracts/contract_topic_of_interests.json
[QA] :
the contract json format to topics of interest feature 
References: https://github.com/unmsmfisi-socialapplication/social_app/issues/324
> [QA] contract for topic of interest

- QA/postman_test/QA_postman_test_interests_061023.json
- QA/postman_test/QA_postman_test_login_061023.json
there's the test made in postman for the feature of topic of interest of users
reference: https://github.com/unmsmfisi-socialapplication/social_app/issues/326
> [QA] postman topic of interests test

- frontend/src/app/auth/register/constant.tsx
I have created the file constant.tsx, for the registration screen, the code inside this file is in accordance with the constant.tsx example that is on the login screen. The constant.tsx file is used to validate the fields that the user will fill out to register on the platform.
> Fe validate register use yup

- frontend/src/app/auth/login/constant.tsx
- frontend/src/app/auth/login/page.tsx
> fIX (schema login ) : replace message yuṕ

- frontend/src/test/validation.test.tsx
- frontend/src/utilities/Constant.tsx
fix constant usernameregex , is necesary rectrict number digit
> fix (constant) include restrict digit

- .github/workflows/data_ci.yaml
Remove specific formatter option for github
> Fix: Update data_ci.yaml

- data/models/sentiment_analysis/sa_lr_pyspark.py
- data/models_pg/sentiment_analysis/sa_lr_pyspark_test.ipynb
Modifications were made to the code to parameterize certain settings and variables, making the script more flexible and easier to adapt to different scenarios.
References: #423, @syntx8
> [DATA] refactor: Parameterize model variables

- frontend/.eslintrc.json
- frontend/.prettierrc.json
- frontend/package.json
Adding Eslint and Prettier config files
> Fix: Configure linting and formatter

- backend/.env.example
- backend/pkg/utils/config.go
Maybe the "[" caracters in the .env file produce an error in CD.
> Fix: possible error in cors

- QA/postman_test/QA_postman_test_login_121023.json
Update postman test for login. References: #321, @PaulaRV01
> [QA] feat: Update postman test login

- android/app/src/main/res/drawable/icon_end_call.xml
- android/app/src/main/res/drawable/icon_speaker.xml
- android/app/src/main/res/drawable/round_style.xml
- android/app/src/main/res/layout/call_user.xml
- android/app/src/main/res/layout/conteiner_user_chat.xml
- android/app/src/main/res/values/strings.xml
In this task, the frontend of the options when calling a user from their contact list was created.
> [M] call user contacts

- frontend/src/components/atoms/Input/input.test.tsx
- frontend/src/components/atoms/Input/input.tsx
Adding two tests for input component
> FE_test_input_component

- data/README.md
[DATA] refactor: Data folder structure #498 @ZDev-19 
This Pull request contemplates the the new project structure for data Team in order to enter the second phase of development defined in #411
> [DATA] refactor: Data forlder structure

- data/dataInstagram.py
- data/dataReddit.py
> [DATA]Getting social media data from your API

- data/cloud_platform/convert_dataframe.py
Reference: https://github.com/unmsmfisi-socialapplication/social_app/issues/417 @orlando2400
> [DATA] feat: Convert of raw data to dataframe

- data/cloud_platform/load_csv.py
Query development to load data to a CSV
References: #418 , @Patrickpisana23
> [DATA] load: Format and load dataframe to CSV

- data/execution/sa_lr_pyspark_main.py
- data/models_pg/sentiment_analysis/sa_lr_pyspark_main_test.ipynb
- data/preprocessing/sa_lr_pyspark_preprocessing.py
- data/training/sa_lr_pyspark_training.py
Segments the script into "execution", "preprocessing" and "training" for better model optimization when used or deployed.
A test of the modification is carried out to verify correct performance.
References: #512, @syntx8
> [Data] refactor: sa script splitting

- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/CardFollow/CardFollow.module.scss
- frontend/src/components/atoms/CardFollow/CardFollow.tsx
- frontend/src/components/index.tsx
I created the follow persons component using material UI
> [FE] (Component): FollowPerson

- android/app/src/main/java/com/social/presentation/authentication/LoginFragment.kt
launchWhenCreated deprecated, prevents changes from the PR #539
> [M] fix: pull request #539

- backend/internal/register/infrastructure/registerUserHandler.go
- backend/internal/register/infrastructure/userRepository.go
The query for the database was fixed and now it connects to the schema.
I also fixed the return of the information when registering and now it only shows the email and the user.
Image of the information entered:
image of the information that is returned:
> Be_fix query_register

- data/execution/sp_lr_sklearn_main.py
- data/preprocessing/sp_lr_sklearn_preprocessing.py
- data/training/sp_lr_sklearn_training.py
This task involves organizing spam detection processes within a dataset by segmenting the code into three main sections. The creation of a structured folder and file system aids project clarity and scalability, facilitating maintenance and collaborative development. Clear documentation enhances understanding and usage, with a defined structure reflecting distinct stages of spam detection for improved role allocation and error correction.  References: #511  , @gustavo-guerreros1
> DATA_Spam_detection_processes_division

- android/app/src/main/java/com/social/presentation/authentication/LoginFragment.kt
- android/app/src/main/java/com/social/presentation/authentication/LoginViewModel.kt
The user and password will only saved if the checkbox is checked and the API response code is 200. It is implemented using SharedPreferences
https://github.com/unmsmfisi-socialapplication/social_app/assets/68746844/5684313c-a762-47da-96cf-75a4b618d3d4
> [M] feat: remember user and password

- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/CardFollow/CardFollow.tsx
- frontend/src/components/atoms/TopicFollow/TopicFollow.module.scss
- frontend/src/components/atoms/TopicFollow/TopicFollow.tsx
- frontend/src/components/index.tsx
I did the topic follow component using material ui.
As a result:
> [FE] (Component): TopicFollow

- frontend/src/utilities/Functions.tsx
The distanceLevenshtein function is used to calculate the Levenshtein distance between two text strings. This distance quantifies how many minimal changes (insertions, deletions, or character substitutions) are needed to make two strings equal.
The mostSimilarPhrase function is used to find the most similar phrase in a set of phrases. Use the distanceLevenshtein function to calculate the distance between a reference phrase and the phrases in the set.
Images:
> [FE] feat: add functions distanceLevenshtein and mostSimilarPhrase

- android/app/src/main/java/com/social/data/repository/SocialAppRepositoryImp.kt
- android/app/src/main/java/com/social/data/source/remote/ApiInterface.kt
- android/app/src/main/java/com/social/data/source/remote/dto/RegisterDto.kt
- android/app/src/main/java/com/social/data/source/remote/dto/RegisterUserErrorDto.kt
- android/app/src/main/java/com/social/di/ApiSocialApp.kt
- android/app/src/main/java/com/social/domain/SocialAppRepository.kt
- android/app/src/main/java/com/social/domain/model/Register.kt
- android/app/src/main/java/com/social/domain/model/RegisterBody.kt
- android/app/src/main/java/com/social/domain/model/RegisterData.kt
- android/app/src/main/java/com/social/domain/model/RegisterDataError.kt
- android/app/src/main/java/com/social/domain/usecase/RegisterNewUser.kt
- android/app/src/main/java/com/social/presentation/authentication/AuthenticationUseCase.kt
- android/app/src/main/java/com/social/presentation/authentication/RegisterEvent.kt
- android/app/src/main/java/com/social/presentation/authentication/RegisterFragment.kt
- android/app/src/main/java/com/social/presentation/authentication/RegisterUserState.kt
- android/app/src/main/java/com/social/presentation/authentication/RegisterUserViewModel.kt
- android/app/src/main/java/com/social/utils/Resource.kt
**Summary**
Feature Register a new user using the app is implemented.
**Steps:**
1. Put an username
2. Put an email
3. Put a password
4. If the email exists yet will appear a toast with the message: "Email already in use" and dont register the user
5. If the email doesnt exists will appear a toast with the message: "Registrado" and register the user.
https://github.com/unmsmfisi-socialapplication/social_app/assets/68746844/407f54d6-00b1-43c8-a71f-8b7a80f846e5
> [M] feat Register new user

- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/TopicFollow/TopicFollow.module.scss
- frontend/src/components/atoms/TopicFollow/TopicFollow.tsx
- frontend/src/components/index.tsx
I fix the topic follow component that I did because it wasn't upload correctly, that's because I delete this component in order to put the "search component" so now I put this component.
> [FE] Topic Follow Component

- android/app/src/main/res/layout/fragment_user_profile.xml
- android/app/src/main/res/values/strings.xml
Correction of designs and assignment of identifiers
There was a confusion with the design in figma as it changed for different User Stories (HU).
> [M] profile user upload

- data/execution/pc_lr_main.py
- data/preprocessing/pc_lr_preprocessing.py
- data/training/pc_lr_training.py
The post classification model was created using LSTM for use. 
References: #588 , @orlando2400
> [DATA] feat: Add Post Classification with LSTM

- android/app/src/main/res/drawable/icon_clear.xml
- android/app/src/main/res/layout/item_cover_photo_specifications.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/strings.xml
In this task, the item was created for the modal that appears when uploading a cover photo to the user's profile. It should be noted that the text that indicates an error when uploading a photo is visibility = gone.
> [M] cover photo specifications

- data/execution/sa_lr_pyspark_main.py
- data/models/sentiment_analysis/pyspark_ls_script.py
- data/models_pg/sentiment_analysis/sa_logistic_regression_pyspark.ipynb
- data/models_pg/sentiment_analysis/sa_lr_pyspark_main_test.ipynb
- data/models_pg/sentiment_analysis/test_sa_lr_pyspark_preprocessing.py
- data/models_pg/sentiment_analysis/test_sa_lr_pyspark_training.py
- data/preprocessing/sa_lr_pyspark_preprocessing.py
- data/training/sa_lr_pyspark_training.py
**[Data] feat: sa script splitting for cloud migration**
Segments the script into "execution", "preprocessing" and "training" for
better model optimization when used deployed.
References: #655 , @syntx8
**[Data] feat: Improved sa model for cloud migration**
This task seeks to improve the performance of sentiment analysis
designed for the cloud migration landscape.
References: #655, @syntx8
> Data improve sa model for cloud migration

- android/app/build.gradle.kts
- android/app/src/androidTest/java/com/social/profileTest/EditProfileFragmentTest.kt
- android/app/src/androidTest/java/com/social/utilsTest/BaseAdapterTest.kt
- android/app/src/androidTest/java/com/social/utilsTest/ValidationTest.kt
- android/app/src/main/java/com/social/presentation/profile/EditProfileFragment.kt
- android/app/src/main/java/com/social/presentation/publications/ListPostFragment.kt
> [M] test adapter's and validations

- frontend/src/utilities/Functions.tsx
Create a function that receives as a parameter a text input and an array of statements.
The purpose of creating this function is to filter the words that the user is typing and give him suggestions of possible words that he may be looking for.
Create this function in src/utilities folder ("Functions" file).
Next issue: Test of this function.
***********************************************************************************************************************
create functión: findMarchingWords
The "findMatchingWords" function takes two arguments: "text", which is a text string, and "words", which is an array of strings. First, it checks to see if the string "text" is empty, in which case it returns an array with a message indicating that the entry is empty. Then, search the "words" array …
> FE: function findMarchingWords

- android/app/google-services.json
**Summary**
Add google services json file to fix the build project
**Image**
> [M] Fix: build project adding googleservicesjson

- frontend/src/app/intranet/page.tsx
- frontend/src/components/atoms/Search/Search.scss
- frontend/src/components/atoms/Search/Search.tsx
- frontend/src/components/molecules/CommentThink/index.tsx
- frontend/src/components/organisms/RightBar/RightBar.tsx
fix , components atoms , also add style in components , too order in template
> fix ( atoms ) : search

- data/baseline_testing.py
- data/models/sentiment_analysis/pyspark_ls_script.py
- data/models/spam_detector/sp_Create_script_model_Logistic_Regression_Parametrizacion.py
Add Baseline model script in Data folder according to issues #592 and #618
> [DATA] feat: Add Baseline Testing

- android/app/build.gradle.kts
- android/app/src/main/java/com/social/presentation/interaction/chats/ChatScreenFragment.kt
- android/app/src/main/java/com/social/presentation/interaction/chats/ListChatsFragment.kt
- android/app/src/main/res/drawable/icon_sticker.xml
- android/app/src/main/res/drawable/rounded_border_left.xml
- android/app/src/main/res/drawable/rounded_border_right.xml
- android/app/src/main/res/layout/fragment_chat_screen.xml
- android/app/src/main/res/layout/fragment_list_chat.xml
- android/app/src/main/res/layout/fragment_user_profile.xml
- android/app/src/main/res/layout/item_emoji_text_view.xml
- android/app/src/main/res/navigation/navigation.xml
- android/app/src/main/res/values/strings.xml
In this task, the emojis and stickers for the chat were created. It should be noted that the "vanniktech:emoji-google" library was used.
> [M] implementation emojis and stickers

- data/pg_bd/BI/migration/df_conection_test.py
create a new table for test
Reference: #682, @beltocas
> [DATA] feat: New conection python with postgresql

- frontend/src/app/test/page.tsx
- frontend/src/components/index.tsx
- frontend/src/components/molecules/UserChatCTA/index.scss
- frontend/src/components/molecules/UserChatCTA/index.tsx
on click on 3 dots shows user cta options:
> FE_user_chat_cta_component

- backend/internal/post/application/postUseCase.go
- backend/internal/post/domain/model.go
- backend/internal/post/helpers/helpers.go
- backend/internal/post/infrastructure/postHandler.go
- backend/internal/post/infrastructure/postRepository.go
- backend/internal/post/router.go
- backend/internal/post/tests/postHandler_test.go
An endpoint, getall, has been added to retrieve a paginated list of posts. The repository functions have been updated to support database connections.
-   User Validation: A validation has been added to ensure that the user for whom the post is being created exists.
-   Domain Structure Enhancement: New structures have been introduced to the domain to facilitate pagination.
-   Domain Structure Refactoring: The domain structures have been refactored for improved organization and clarity.
-   Testing: Tests have been added to validate the proper functioning of the new endpoints
```json
{
"userId": 2,
"title": "Test",
"description": "Esto es una descripción de ejemplo para la publicación.",
"hasMultimedia": true,
"public": false,
"multimedia": "https://ejemplo.com/imagen.jpg"
}
```
> BE_Update_Endpoint_Post

- QA/contracts/contract_registration.json
The modification was carried out in response to coordination with the team leaders, who requested the inclusion of unsuccessful scenarios alongside the successful scenario in the user registration contract. These unsuccessful scenarios have been designed realistically and are based on the latest project code updates.
- Successful Scenario #750 
- Unsuccessful Scenarios #751 
#746 @luzelenatt
> [QA] Registration contract update

- .github/dependabot.yml
Dependabot is a tool that automates dependency updates to ensure our project remains secure and up-to-date. This PR aims for implementing Dependabot in our project. Resolving the following issue #581
> [DEVOPS] Implementing dependabot

- data/pg_bd/BI/script/bi_log.sql
This Pull Request explains the incorporation of a Log table for our BI processes. Adds a first functionality to detect if the process goes through INSERT, DELETE or UPDATE.
> [DATA] Log table for BI processes

- QA/postman_test/QA_postman_test_comments.json
Test the comments functionality in postman
> [QA] Comments functionality testing

- android/app/src/main/java/com/social/data/repository/SocialAppRepositoryImp.kt
- android/app/src/main/java/com/social/data/source/remote/ApiInterface.kt
- android/app/src/main/java/com/social/domain/SocialAppRepository.kt
- android/app/src/main/java/com/social/domain/usecase/RegisterNewUser.kt
**Summary**
Solved the bug in the model reference to use the register for a new user
> [M] Fix the model reference to classes in register new user

- QA/contracts/contract_login.json
The purpose of this pull request (PR) is to update the login contract, including responses according to the set status codes. For additional information, you can review the following issues: 
#753 
#757 
#754 
#756
> [QA] Update contract for login

- QA/contracts/contract_registration.json
The purpose of this pull request (PR) is to update the login contract, including responses according to the set status codes. For additional information, you can review the following issues:
#746 
#748 
#750 
#751
> [QA] Update contract for registration

- android/app/build.gradle.kts
- android/app/src/test/java/com/social/domain/usecase/RegisterNewUserTest.kt
**Summary**
Unit test using Mockk library. This testing was implemented for RegisterUser UseCase, the core of the business
**Images**
**_Test passed: 4 / 4_**
> [M] Test Register new user use case

- android/app/src/main/java/com/social/data/repository/SocialAppRepositoryImp.kt
- android/app/src/main/java/com/social/data/source/remote/ApiInterface.kt
- android/app/src/main/java/com/social/data/source/remote/dto/LoginDto.kt
- android/app/src/main/java/com/social/domain/SocialAppRepository.kt
- android/app/src/main/java/com/social/domain/model/Login.kt
- android/app/src/main/java/com/social/domain/model/LoginUserData.kt
- android/app/src/main/java/com/social/domain/usecase/RegisterNewUser.kt
- android/app/src/main/java/com/social/domain/usecase/ValidateCreatePost.kt
- android/app/src/main/java/com/social/domain/usecase/ValidateUser.kt
- android/app/src/main/java/com/social/presentation/authentication/LoginDataState.kt
- android/app/src/main/java/com/social/presentation/authentication/LoginFragment.kt
- android/app/src/main/java/com/social/presentation/authentication/LoginViewModel.kt
- android/app/src/main/java/com/social/utils/Resource.kt
This PR fixes the #796 issue.
**Context**
When the user inputs their username and password the app returns an error message related the response of Login API
**Solution**
I have to change the LoginResponse data class model. Now returns an object if the server response is 200, in this object returns a string value named "token". Also I have to change the reference of repository, Api interface, repositoryimp with this new value.
Finally, in the use case named Validateuser, I have to change to return this new model
**Extras**
I have to modify other uses cases because I modified the Resource file
> [M] Fix Login access using the mobile app

- backend/internal/post/application/postUseCase.go
- backend/internal/post/domain/model.go
- backend/internal/post/infrastructure/postHandler.go
- backend/internal/post/infrastructure/postRepository.go
- backend/internal/post/router.go
- backend/internal/post/tests/postHandler_test.go
A new endpoint has been added to fetch posts by ID. Additionally, modifications were made to the "get all" post endpoint to list only public posts.
1. Added a conditional statement (public = true) in the query of the getall repository to list only public posts.
2. Introduced a new method in the repository to retrieve posts by ID.
3. Adjusted the response of the created post to align with the specifications outlined in the post creation contract.
4. Tests were updated to validate error cases independently and not rely on database records.
> BE_Feat_Get_Post_by_Id

- QA/postman_test/QA_postman_test_topic_of_interest_101123.json
added tests on the functionality of topics of interest, based on issue https://github.com/unmsmfisi-socialapplication/social_app/issues/741
> [QA] Test for Topic of Interests feature in Postman

- data/notebook/spam_detector/Implementation_of_Azure_functionalities_for_Machine_Learning.py
- data/notebook/spam_detector/config_azure.json
- data/notebook/spam_detector/sp_model_sklearm.py
The issue  involves configuring the Azure ML environment for the spam detector. The process includes loading configuration from the JSON file using the json library, defining Azure credentials automatically with DefaultAzureCredential(), extracting key variables for the Azure ML environment, and using ResourceManagementClient to create or update resource groups. The config_azure.json file contains essential configuration details for authentication and environment setup, allowing external management for enhanced security. The process description covers loading configuration, defining credentials and variables, interacting with Azure Resource Management, and configuring the Azure ML environment using Workspace.create().   References: #837  , @gustavo-guerreros1
> DATA_Provision_and_Configure_Azure_ML_Environment_for_Spam_Detector

- data/notebook/spam_detector/Implementation_of_Azure_functionalities_for_Machine_Learning.py
- data/notebook/spam_detector/Uploading Trained Spam Detection Model to Azure ML.py
- data/notebook/spam_detector/config_azure.json
In this activity, we will upload the trained spam detection model, developed using Python's scikit-learn library, to Azure Machine Learning. This involves leveraging the Azure ML Python SDK to store the model either in Azure Blob Storage or within a designated folder in the Azure ML workspace. The uploaded model can then be easily accessed and deployed for further use within the Azure ML environment. References: #846  , @gustavo-guerreros1
> DATA_Uploading_Trained_Spam_Detection_Model_to_Azure_ML

- frontend/src/app/test/page.tsx
- frontend/src/components/index.tsx
- frontend/src/components/molecules/ReportPublication/index.scss
- frontend/src/components/molecules/ReportPublication/index.tsx
The component was created, and logic was applied to enable the selection of the reason for the report.
> fe_modal_report_publication

- frontend/src/app/test/page.tsx
- frontend/src/components/molecules/DetailsImage/detailImage.test.tsx
- frontend/src/components/molecules/DetailsImage/index.scss
- frontend/src/components/molecules/DetailsImage/index.tsx
The designs for the component have been fixed, and some properties have been added for easy implementation and customization when deploying it. The unit test has also been modified to align with the new component.
> FE_fix_details_user_image

- frontend/src/components/molecules/Comment/comment.tsx
- frontend/src/test/components/molecules/Comment.test.tsx
According to what is indicated in issue #848. The comment.test.tsx test file was created, where the rendering of the Comment is tested.
Additionally, the test was validated by executing the "npm run test" command.
Capture of evidence is attached:
> Add test comment molecule component

- data/postgresql_bd/store procedure/bi.process_bi_postclassification.sql
- data/postgresql_bd/store procedure/bi.process_bi_sentimental.sql
- data/postgresql_bd/store procedure/bi.process_bi_spam.sql
This is in response to issue number: https://github.com/unmsmfisi-socialapplication/social_app/issues/819
> DATA_BI_DataFactory

- data/cloud_platform/sentiment_analysis/.dockerignore
- data/cloud_platform/sentiment_analysis/.gitignore
- data/cloud_platform/sentiment_analysis/Dockerfile
- data/cloud_platform/sentiment_analysis/main.py
- data/cloud_platform/sentiment_analysis/preprocessing.py
- data/cloud_platform/sentiment_analysis/requirements.txt
- data/cloud_platform/sentiment_analysis/storage.py
- data/notebook/sentiment_analysis/sa_endpoint_firebase_storage.ipynb
- data/test/sa_test_preprocessing.py
- data/test/sa_test_storage.py
**[Data] feat: cloud deployed ML service**
Implement the necessary code to be able to deploy the sentiment analysis model in the cloud.
Uses Docker to facilitate the deployment.
References: #826, @syntx8
> [Data] feat: cloud deployed ML service for SA

- android/app/src/test/java/com/social/domain/usecase/ValidateUserTest.kt
**Test Cases**
1. Successful Authorization
2. User not found
3. Bad credentials
**Testing**
All Test passed successfully
> [M] Unit Testing ValidateUser use case

- android/app/src/main/java/com/social/data/repository/SocialAppRepositoryImp.kt
- android/app/src/main/java/com/social/data/source/local/SocialDAO.kt
- android/app/src/main/java/com/social/data/source/local/SocialDB.kt
- android/app/src/main/java/com/social/data/source/local/UserEntity.kt
- android/app/src/main/java/com/social/di/ApiSocialApp.kt
- android/app/src/main/java/com/social/domain/SocialAppRepository.kt
- android/app/src/main/java/com/social/domain/model/UserM.kt
**Summary:**
> Using Room for create a local database and User entity to save the user data while the user is logging, also is available to list his attributes, update his informations and delete when he logouts
**Architecture:**
> Green rectangle is implemented in this PR
> 
> <img width="653" alt="image" src="https://github.com/unmsmfisi-socialapplication/social_app/assets/68746844/32db8ab7-a163-4d0e-af29-7a0c70eb2cbe">
**Implementation:**
> In this PR I defined the database in an abstract class named _SocialDB_, but first of all I defined the user entity  that is a dataclass with the attributes of the user table. In another DAO interface I defined the querys that we will use (select, insert, update and delete).
> 
> In ApiSocialApp I send another parameter for the suppliers, added the …
> [M] feat: User entity created for local database using Room

- data/test/mldeployment/pc_lr_main.py
- data/test/pc_test.py
- data/test/preprocessing/pc_lr_preprocessing.py
- data/test/training/pc_lr_training.py
Improved data preprocessing for the lstm model, and added tagged post download functionality. 
References: #821 , @orlando2400
> [DATA] feat: Post-tag export and model enhancement

- data/cloud_mldeployment/sentiment_analysis/main.py
- data/cloud_mldeployment/sentiment_analysis/requirements.txt
- data/cloud_mldeployment/sentiment_analysis/storage.py
- data/test/sa_test_storage.py
The goal is to improve storage for sentiment analysis by migrating from Firebase Storage to Azure Storage.
It also adds the respective test to the storage module for Azure.
References: #893, @syntx8
> [Data] refactor: Enhancing Storage in Azure for SA

- data/IaC/instructions.txt
- data/IaC/management_resource/resource_group/main.tf
- data/IaC/management_resource/resource_group/variables.tf
- data/IaC/management_user/main.tf
- data/IaC/management_user/variables.tf
1. **Previous considerations**
- This Pull Request is the continuation of PR #876 and #882.
2. **Task Objetive**
- The objective of this Pull Request is the implementation of root resources for creating the Resource Group, Groups and Users using the Terraform tool.
3. **Requirements**
Tool Name | Definition
-- | --
Azure CLI v2.54.0  | Is a command-line tool that makes it easy to interact with Microsoft Azure services and resources.
Terraform v1.6.4 | They are an essential organizational tool that helps users manage and keep their resources organized.
4. **Proccess**
`terraform init`
`terraform plan`
`terraform apply`
5. **Synchronization in Azure Cloud**
Group Resource:
Groups:
Users:
6. **Next Steps**
- The next step is the deployment of the SQL database in Azure Cloud.
> [DATA] Configuring IaC for GroupResource, Groups and Users

- backend/internal/router/router.go
- backend/internal/router/router_test.go
Now the application's routing mechanism has been enhanced to include robust security measures.  TokenValidator middleware has been integrated  to ensure that only authenticated users can access sensitive endpoints. This update introduces a clear distinction between protected and publicly accessible routes.
The application now utilizes two subrouters:
-   **protectedRoutes**: This subrouter is wrapped with TokenValidator middleware. Any routes mounted to `protectedRoutes` require a valid authentication token to access, ensuring that these endpoints are exclusively available to authenticated users.
-   **freeRoutes**: This subrouter is designed for endpoints that do not require user authentication. It is used primarily for the `/login` and `/register` endpoints, allowing new and returning …
> [BE] Integration of TokenValidator Middleware for Enhanced App Security

- data/notebook/spam_detector/sp_sklearn_inference.py
- data/notebook/spam_detector/test_sp_skearn_inference.py
This activity involves developing an inference script in Python, named inference.py, to facilitate predictions using the pre-trained spam detection model. The script includes essential functions, such as init() for service initialization and run(raw_data) for performing predictions. It ensures consistency with the training script's text cleaning process and should be tested locally before deployment to Azure ML. The script needs to be included in the Azure ML deployment configuration, emphasizing the importance of local testing for seamless implementation.  References: #854  , @gustavo-guerreros1
> Implementation_of_the_Inference_Script_for_the_Spam Detector

- .gitignore
- data/database_management/connection_details/conexion_sql.py
- data/test/connection_sql_test.py
Add the connection for Azure SQL Database and test script
> [DATA] Add sql_server  azure db connection

- android/app/src/main/java/com/social/presentation/home/NewPostFragment.kt
- android/app/src/main/res/layout/fragment_new_post.xml
- android/app/src/main/res/values/strings.xml
A maximum of 6 photographs can be attached and they are deleted by tapping. It remains to attach videos, gifs and location.
https://github.com/unmsmfisi-socialapplication/social_app/assets/67835220/3a2cafbe-19e3-46d8-9d6e-732e73e75939
> [M] attach photos new post

- backend/internal/post/application/postUseCase.go
- backend/internal/post/domain/model.go
- backend/internal/post/infrastructure/postHandler.go
- backend/internal/post/infrastructure/postHandler_test.go
- backend/internal/post/infrastructure/postRepository.go
- backend/internal/post/router.go
The Edit Post component is an essential feature of the social media platform, allowing users to update their existing posts. This functionality enhances user engagement and content accuracy.
The Edit Post feature is integrated via a RESTful API, utilizing the **PUT** method to handle post update requests efficiently. This synchronous operation ensures that users receive immediate feedback regarding their update request.
Access the Edit Post service through the following endpoint: `https://{server}:{port}/post/update/{id}`
The unique post ID is required in the URL path to identify the post to be edited:
| Field | Description | Example |
|-------|-------------|---------|
| id    | Unique identifier of the post | 123 |
The request body should include the following fields for updating a post: …
> [BE] feat: Implement Edit Post Component

- frontend/src/components/atoms/Link/Link.test.tsx
I did the test for the search component.
So first i created the file for test in link component file:
The provided code contains unit tests for the React component called WBasicsLink. These tests are performed using the @testing-library/react library and are divided into two cases. The first test checks whether the component renders correctly with the default values, including the presence of the text "link", a default link (href="#"), and an underline (textDecoration: 'underline'). The second test evaluates the performance of the component when custom properties are passed to it, verifying that the resulting link has the text "custom link", a specific link (href="https://example.com"), and the absence of an underline . (textDecoration: 'none'). These tests ensure that the WBasicsLink …
> [FE] (Test): Link Component 

- QA/test_development/QA_Develop_Environment.postman_environment.json
This pull request addresses the first part of the issue #803, aimed at updating the QA folder structure and environment configuration in the repository. The changes made in the 'develop' branch are as follows:
Created a folder named test_development as part of the proposed structure update.
Uploaded the Postman environment file QA_Develop_Environment.postman_environment to facilitate testing for each collection (modules of the social application).
Added: test_development/QA_Develop_Environment.postman_environment
**Reference:** [#803](https://github.com/unmsmfisi-socialapplication/social_app/issues/803)
> [QA] Update QA Folder Structure and Environment Configuration - Part 1

- QA/test_production/QA_Production_Environment.postman_environment.json
This pull request addresses the second part of issue #803. In this update, the test_production folder has been created, and the Postman environment file QA_Production_Environment.postman_environment has been added. This file includes the current deployment link of the social application. It's crucial to note, as mentioned in the issue, that when merging with the 'main' branch, the URL of the social application in production should be updated according to the information provided by the DevOps team.
**Goals:**
> Maintain an organized structure for tests in the production environment.
> Prepare the configuration for future updates to the URL of the social application in production.
**Reference:** #803
> [QA] Update QA Folder Structure and Environment Configuration - Part 2

- QA/test_development/Registro.postman_collection.json
**Key Points:**
**_Request Setup:_**
- The POST request is directed to the {{url}}/register endpoint.
- Details such as email, username, and password are included in the request body.
**_Test Script:_**
- The test script covers various checks to ensure different aspects of the registration process.
- Validations include the correct format of the request body, email format, length and format of the username, password format, etc.
- It verifies the response status, response message, and response time.
- Global variables status and message are set for later use in subsequent tests.
**_Prerequest Script:_**
- Global variables status and message are configured before sending the request.
**_Usage of Global Variables:_**
- Global variables status and message are stored and later utilized for …
> [QA] Test for Successful Registration

- frontend/src/app/intranet/profile/page.tsx
- frontend/src/app/test/page.tsx
- frontend/src/components/atoms/SelectText/selectText.test.tsx
- frontend/src/components/atoms/Tag/tag.tsx
- frontend/src/components/organisms/SideBar/SideBar.tsx
- frontend/src/test/components/atoms/CardFollow.test.tsx
- frontend/src/test/components/atoms/CircleIcon.test.tsx
- frontend/src/test/function.test.tsx
Page profile dont connect with proyect
use page Porfile to connect with proyect
> FE fix (profilePage) : connect with proyect

- backend/migrations/0000000026_create_post_reports_table.down.sql
- backend/migrations/0000000026_create_post_reports_table.up.sql
The `SOC_APP_POST_REPORTS` table is a crucial component of the social networking application. It is designed to store and manage reports made by users against posts that may violate community standards or contain inappropriate content.
| Column        | Data Type         | Constraints                                      | Description                                                                   |
|-----------------|-------------------|--------------------------------------------------|-------------------------------------------------------------------------------|
| report_id     | serial            | PRIMARY KEY                                      | Unique auto-incrementing identifier for each report.                         |
| post_id       | bigint NOT NULL   | FOREIGN KEY …
> [BE] Implementation of soc_app_post_reports Table for Post Reporting Mechanism

- android/app/src/main/java/com/social/MainActivity.kt
- android/app/src/main/java/com/social/presentation/profile/UserProfileFragment.kt
The session is saved when the application is closed whenever you decide to save the data.
https://github.com/unmsmfisi-socialapplication/social_app/assets/67835220/914d8016-a0d1-403f-ab1e-6950c8f43080
> [M] session persistence

- backend/internal/follow/application/followUseCase.go
- backend/internal/follow/application/followUseCase_test.go
- backend/internal/follow/infrastructure/followHandler.go
- backend/internal/follow/infrastructure/followRepository.go
- backend/internal/follow/router.go
The View Profile Following Profiles API allows clients to retrieve a list of profiles that a specific user profile is following on the social media platform.
The API utilizes the HTTP GET method to fetch the profiles that a particular user profile is following.
Access the View Profile Following Profiles service through the following endpoint:
`http://localhost:3333/follow_profile/profile_following_profiles`
The client should provide the following parameters in the request:
- `profile_id` (integer): The unique identifier of the user profile for which following profiles are to be retrieved.
- `page_size` (integer): The page size for result pagination.
- `page_number` (integer): The page number for result pagination.
**Example Request:**
```http
GET …
```
> [BE] feat: View user profiles followed by a user profile - Endpoint

- data/cloud_mldeployment/sentiment_analysis/main.py
> [Data] fix: SA add environment variable in main

- android/app/src/main/java/com/social/presentation/home/HomeFragment.kt
- android/app/src/main/res/drawable/post_icon_heart_bold.xml
- android/app/src/main/res/drawable/post_icon_like_bold.xml
- android/app/src/main/res/layout/comments.xml
- android/app/src/main/res/layout/fragment_edit_profile.xml
- android/app/src/main/res/layout/fragment_user_profile.xml
- android/app/src/main/res/layout/item_comment.xml
In this issue the integration of comments in the home posts was carried out.
Results:
> [M] integrate comment post

- data/cloud_mldeployment/post_classification/azure_storage.py
- data/cloud_mldeployment/post_classification/main.py
- data/cloud_mldeployment/post_classification/requirements.txt
- data/test/pc_test_azure_storage.py
- data/test/pc_test_main.py
The code is implemented to upload the post-classification model to the azure cloud, the final file that generates the model is saved in a storage container.
References: #827 , @orlando2400
> [DATA] feat: Azure cloud service deployed for Post Classification

- data/IaC/azure_ml_envirorment/main.tf
- data/IaC/azure_ml_envirorment/variables.tf
This actions we can do before or after pr #1026 .
What will happen is that the following services will be created :
Service Name              | Description                                           |
| ------------------------- | ----------------------------------------------------- |
| Azure Container           | Container service for deploying and managing containers |
| Key Vault                 | Securely store and manage sensitive information, such as secrets, encryption keys, and certificates |
| Application Insights      | Application performance and usage monitoring          |
| Key Vault Access Policy   | Defines the permissions and access control for Key Vault |
| Azure ML                  | Azure Machine Learning service for building, training, and deploying machine learning …
> creation services workspace related

- .gitignore
- data/API/conexion_sql.py
- data/API/load_model_results.py
In this PR the logic for model results is developed using libraries like:
- Sqlalchemy
- UrlLib
- Requests
This for data management overall , also SQL Alchemy reduce complexity that DDL approach couldnt do
> [DATA] Migration of results to Azure DB

- backend/internal/register/domain/model.go
- backend/internal/register/domain/model_test.go
- backend/internal/register/infrastructure/registerUserHandler.go
- backend/internal/register/infrastructure/registerUserHandler_test.go
It was identified that the endpoint lacked validations to prevent the creation of users without a username. Additionally, the response was being sent as plain text and with a method different from the project's standard.
- A method was added to validate that the sent request contains all the required fields.
- Tests were added for the domain functions.
- The handler code was refactored by creating our UserRequest and UserResponse structures.
- Handler tests were refactored to align with the new response and utilize the defined models..
> Be_fix_register

- frontend/src/app/test/page.tsx
- frontend/src/components/molecules/ChatInfo/index.tsx
Add Info chat molecule and testing in testing page
> [FE] Add Info chat molecule and testing

- data/API/api_deployment.py
this model is a premilinar deployment
Reference: #906, @beltocas
> [DATA] feat: preliminar deploy

- QA/contracts/contract_login.json
The login contract was updated, regarding the scenario with invalid password entry.
**Modifications:**
- Development Mock URL Update
- Added example as a guide for other teams.
> [QA] Update login contract for invalid password

- QA/contracts/contract_login.json
The login contract was updated, regarding the unsuccessful scenario when trying to log in with a username that does not exist in the social application.
**Modifications:**
- Development Mock URL Update
- Added example as a guide for other teams.
> [QA] Update login contract for non-existing user

- QA/contracts/contract_registration.json
The user registration contract was updated to show more specifically what considerations must be taken for user registration correctly.
**Modifications:**
- Update of the development URL.
- The body was updated, based on the Figma provided by UX/UI, they considered full_name and confirm_password fields.
- An example was included for better understanding by other development teams.
> [QA] Update user registration contract successful

- QA/test_development/Login.postman_collection.json
This pull request updates the Postman test for the "Login with Non-Existent User" scenario in the "Login" test case. The changes include:
Updated the request body to reflect the use of a non-existent username (notuser2) and a valid password (TestP@ss123).
```
{
"user_name": "notuser2",
"password": "TestP@ss123"
}
```
`Status Code: 404 Not Found
`
**Response:**
```
{
"status": "NOTFOUND",
"message": "User not found"
}
```
- Updated the script to set the request body with the non-existent username and valid password.
- Saved the expected values of 'status' and 'message' in global variables.
```
// Pre-request script
pm.request.body.raw = JSON.stringify({
"user_name": "notuser2",
"password": "TestP@ss123"
});
// Save …
```
> [QA] Postman test update for non-existent user login scenario

- .gitignore
- data/bussines_analytics/data_transformation/Automation_sp/Auto_Runbook_post.ps1
- data/bussines_analytics/data_transformation/Automation_sp/Auto_Runbook_sentiment.ps1
- data/bussines_analytics/data_transformation/Automation_sp/Auto_Runbook_spam.ps1
Added powerShell scripts to automate automated procedures
references: #951 , @Patrickpisana23
> [DATA] feat:  automation azure Runbooks

- QA/test_development/Login.postman_collection.json
This pull request updates the Postman test for the "Login with Invalid Request Payload" scenario in the "Login" test case. The changes include:
Updated the request body to reflect the use of a non-existent username (notuser3) and an invalid password (badpass@123).
```
{
"user_name": "notuser3",
"password": "badpass@123"
}
```
`Status Code: 400 Bad Request`
**Response:**
```
{
"message": "Invalid request payload"
}
```
- Updated the script to set the request body with the non-existent username and invalid password.
- Saved the expected values of 'status' and 'message' in global variables.
```
// Pre-request script
pm.request.body.raw = JSON.stringify({
"user_name": "notuser3",
"password": …
```
> [QA] Postman test update for login scenario with invalid request payload

- QA/test_development/Login.postman_collection.json
This pull request updates the Postman test for the "Login with Server Error" scenario in the "Login" test case. The changes include:
Updated the request body to reflect the use of a valid username (testuser3) and password (TestP@ss123).
```
{
"user_name": "testuser3",
"password": "TestP@ss123"
}
```
`Status Code: 500 Internal Server Error`
**Response:**
```
{
"message": "Error during authentication"
}
```
- Updated the script to set the request body with the valid username and password.
- Saved the expected values of 'status' and 'message' in global variables.
```
pm.request.body.raw = JSON.stringify({
"user_name": "testuser3",
"password": "TestP@ss123"
});
// Save the …
```
> [QA] Postman test update for login scenario with server error

- frontend/src/components/atoms/ButtonAnimated/buttonAnimated.test.tsx
- frontend/src/components/atoms/ButtonAnimated/buttonAnimated.tsx
- frontend/src/components/atoms/ButtonSquare/ButtonSquare.tsx
- frontend/src/components/atoms/ButtonSquare/buttonsquare.test.tsx
The initial code was: 
And the previous test was:
Then; 
Using this code, the results was:
**Test Description:**
This test verifies that the SquareButton component's onClick handler is executed when the button is clicked.
**Test Execution Steps:**
- const onClickMock = jest.fn(): Creates a mock function using Jest's jest.fn().
- render(<SquareButton onClick={onClickMock} />): Renders the SquareButton component with the mock function as the onClick handler.
- const outerButton = screen.getByTestId('outer-button'): Retrieves the button element with the data-testid attribute 'outer-button'.
- fireEvent.click(outerButton): Simulates a click event on the button using the fireEvent.click function from @testing-library/react.
- expect(onClickMock).toHaveBeenCalled(): Asserts that the mock …
> [FE] (Test): Add OnClick Function to ButtonSquare Test

- frontend/src/components/atoms/ButtonAnimated/buttonAnimated.test.tsx
- frontend/src/components/atoms/ButtonAnimated/buttonAnimated.tsx
I did changes on buttonAnimated
The initial code was:
The results of the test, was:
**'executes the onClick handler when clicked':**
This test ensures that the WButtonMotion component correctly executes the provided onClick handler when the button is clicked.
**Execution Steps:**
- const onClickMock = jest.fn(): Creates a mock function using Jest's jest.fn().
- render(<WButtonMotion dataTestid="buttonAnimated" text="Go" onClick={onClickMock} />): Renders the WButtonMotion component with the mock function as the onClick handler.
- fireEvent.click(getByTestId('buttonAnimated')): Simulates a click event on the button using fireEvent.click from @testing-library/react.
- expect(onClickMock).toHaveBeenCalled(): Asserts that the mock function onClickMock has been called by …
> [FE] (Test): Add Functions to Button Animated Test

- android/.idea/androidTestResultsUserPreferences.xml
- android/app/build.gradle.kts
- android/app/src/androidTest/java/com/social/homeTest/HomeFragmentTest.kt
- android/app/src/androidTest/java/com/social/homeTest/PostRepositoryImpTest.kt
- android/app/src/main/java/com/social/presentation/home/HomeFragment.kt
Two files were created to carry out tests on the components of the publications (post). These files are:
1. PostRepositoryImpTest.kt
2. HomeFragmentTest.kt
> [M] Junit Test Post

- QA/test_development/Registro.postman_collection.json
This pull request (PR) modifies the Postman test for the "User Registration with Invalid Password" scenario. The changes include:
- The request body has been updated to simulate a user registration attempt with an invalid password.
```
{
"full_name": "Pedro Caceres",
"email": "test3@example.com",
"user_name": "testuser3",
"password": "badpass",
"confirm_password": "badpass"
}
```
`Status Code: 400 Bad Request`
**Response:**
```
{
"message": "Not secure password"
}
```
- The script has been updated to save the values of 'status' and 'message' in global variables.
```
pm.globals.set("status", "ERROR");
pm.globals.set("message", "Not secure password");
```
**Tests Update:**
- A …
> [QA] Update Postman Test for User Registration with Invalid Password

- QA/test_development/Registro.postman_collection.json
This pull request (PR) modifies the Postman test for the "User Registration with Existing Username" scenario. The changes include:
- The request body has been updated to simulate a user registration attempt with a username that is already in use.
```
{
"full_name": "Maria Solis",
"email": "test4@example.com",
"user_name": "myuser12", // This username is already in use
"password": "TestP@ss123",
"confirm_password": "TestP@ss123"
}
```
`Status Code: 409 Conflict`
**Response:**
```
{
"message": "Username already in use"
}
```
The script has been updated to save the values of 'status' and 'message' in global variables.
```
pm.globals.set("status", "ERROR"); …
```
> [QA] Update Postman Test for User Registration with Existing Username

- QA/test_development/Registro.postman_collection.json
This pull request (PR) modifies the Postman test for the "User Registration with Email in Use" scenario. The changes include:
- The request body has been updated to simulate a user registration attempt with an email that is already in use.
```
{
"full_name": "Carla Sanchez",
"email": "test1@example.com", // Email already registered
"user_name": "testuser2",
"password": "TestP@ss123",
"confirm_password": "TestP@ss123"
}
```
`Status Code: 400 Bad Request`
**Response:**
```
{
"message": "Email already in use"
}
```
The script has been updated to save the values of 'status' and 'message' in global variables.
```
pm.globals.set("status", "ERROR");
pm.globals.set("message", "Email …
```
> [QA] Update Postman Test for User Registration with Email in Use

- QA/test_development/Registro.postman_collection.json
This pull request (PR) modifies the Postman test for the "User Registration with Server Error" scenario. The changes include:
- The request body has been updated to simulate a user registration attempt that results in a server error.
```
{
"full_name": "Juan Salinas",
"email": "test5@example.com",
"user_name": "testuser5",
"password": "TestP@ss123",
"confirm_password": "TestP@ss123"
}
```
`Status Code: 500 Internal Server Error`
**Response:**
```
{
"message": "Internal Server Error. Please try again later."
}
```
The script has been updated to save the values of 'status' and 'message' in global variables.
```
pm.globals.set("status", "ERROR");
pm.globals.set("message", …
```
> [QA] Update Postman Test for User Registration with Server Error

- backend/internal/post/domain/model_test.go
- backend/internal/post/helpers/helpers_test.go
- backend/internal/profile/router.go
- backend/internal/register/router.go
- backend/internal/router/router.go
This PR addresses the pending items from the previous pull requests, focusing on the post module. Tests have been added to validate the functionality of the post module, covering the code developed up to this point. This ensures a more robust and reliable codebase.
Additionally, a refactor of the general router module has been carried out. The code has been restructured to enhance readability, resulting in a cleaner and more comprehensible codebase. This modification contributes to the overall maintainability of the code.
The changes made in this PR aim to improve the quality and reliability of the application, aligning with best practices and ensuring a smoother development process.
> BE_Add_Test_post

- .github/workflows/data-tf-ci.yml
Error in skipping a line to new one for multiline command
> [DEVOPS] Fix: error in running step in CI TF for Data

- QA/postman_test/QA_Stress_postman_Profile.json
We have successfully completed the stress testing of our 'Profile Import' feature. Below are the summarized details and outcomes of the test cases executed.
**Test Name:** Profile Stress Cases
**Test ID:** 240f68f4-7e8f-475e-be39-931406eb8aaf
**Timestamp:** 2023-12-01T15:23:10.815Z
**Total Passes:** 300
**Total Failures:** 0
**Status:** finished
**Started At:** 2023-12-01T15:22:44.796Z
**Total Time:** 18824 ms
**Endpoint:** PUT https://social-app-backend-service-7bg5siys2q-uc.a.run.app/profile/import
**Time Taken:** Average of 187 ms per request
**Response Code:**
```
{
"code": 200,
"name": "OK"
}
```
**Scenarios Tested:**
> **Given:** The profile to be imported is complete and well-formed: 100% pass rate
> **When:** The profile import request is made: 100% pass rate
> **Then:** Should …
> [QA] Stress cases for Profile

- QA/contracts/contract_topic_of_interests.json
`https://31f26148-53be-474d-9a51-fa125946327a.mock.pstmn.io/{{user_id}}/interests/add`
`POST`
`200 OK`
- `Content-Type`: `application/json`
---
**Add a topic successfully with the correct actor and interests**
```json
{
"user_id": "some-valid-user-id",
"interest_id": ["sports", "technology", "travel"]
}
```
```json
{
"status": "OK",
"message": "Topic added successfully"
}
```
`https://31f26148-53be-474d-9a51-fa125946327a.mock.pstmn.io/{{user_id}}/interests/add`
`POST`
`400 BAD REQUEST`
- `Content-Type`: `application/json`
---
**Attempt to add a topic without a correct actor**
```json
{
"user_id": "",
"interest_id": ["sports", "technology", "travel"]
}
```
```json
{
"message": "Invalid request payload: user_id not defined"
}
``` …
> [QA] Update contract topic of interests

- frontend/package.json
- frontend/src/app/auth/404/404.css
- frontend/src/app/auth/404/page.tsx
- frontend/src/components/atoms/ButtonAnimated/buttonAnimated.scss
- frontend/src/test/data/api/api.test.tsx
test in api Services , do get test , and mock && format 404 page in case error
>  DEV fe feat (test) :  do get test && format 404

- .github/workflows/backend-cd.yaml
- .github/workflows/manual-backend-cd.yaml
Added a new workflow who will exit with a status code of 1 if any issues are encountered during the migration process, preventing branch merges until the database migrations are successfully completed.
> [DevOps] feat: Block merging with migrations

- QA/test_development/POST.postman_collection.json
Refactoring JSON Structure for Response Examples and Adding Private Post Creation Example to the Collection.
**Description:** Create a private post.
**Method:** POST
**Endpoint:** https://31f26148-53be-474d-9a51-fa125946327a.mock.pstmn.io/crear-post
**Body:**
```
{
"userId": 123,
"title": "Prueba de publicación en privado",
"description": "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto",
"hasMultimedia": true,
"public": false,
"multimedia": "asdasd/multimedia1.jpg"
}
```
Response:
```
{
"response": {
"Id": 10,
"UserId": 123,
"Title": "Prueba de publicación en privado",
"Description": "Lorem Ipsum es simplemente el texto de relleno de las imprentas y archivos de texto",
"HasMultimedia": true,
"Public": false,
"Multimedia": "asdasd/multimedia1.jpg", …
```
> [QA] Test for Successful Post Create

- QA/test_development/POST.postman_collection.json
**Endpoint:** https://5fff7e05-0538-4ab2-8235-e8976a482701.mock.pstmn.io/crear-post
**Method:** POST
**Body:**
```
{
"userId": 123,
"title": "Publicación con un GIF",
"description": "Descripción de la publicación",
"hasMultimedia": true,
"public": true,
"multimedia": [
"gif1.gif"
]
}
```
**Response**
```
{
"response": {
"Id": 20,
"UserId": 123,
"Title": "Publicación con un GIF",
"Description": "Descripción de la publicación",
"HasMultimedia": true,
"Public": true,
"Multimedia": [
"gif1.gif"
],
"InsertionDate": "2023-11-07T10:00:00.000000000Z",
"UpdateDate": "2023-11-07T10:00:00.000000000Z"
},
"status": "SUCCESS"
}
```
> [QA]: Test for Successful Post Create with GIF Test Case

- backend/internal/comment/infrastructure/commentRepository.go
This PR includes a series of improvements to the Comment Repository functions in our Go codebase, enhancing error handling, input validation, and overall code efficiency.  
In addition, comment updating has been improved to allow dynamic updating of comments. This means that the data sent in the payload will be optional as required by the client. For this, the creation of dynamic SQL queries was implemented to update only the modified fields and a verification of the number of affected rows was added.
Below is the table with the available requests:
| Type | ROUTE             | BODY | SUCCESSFUL RESPONSE |
|  :------:  | :---------------- | :------ | ----: |
| GET | {BASE_URL}/comments |   -   | { "response": [ { }, { } ], "status" : "ok" } |
| GET | {BASE_URL}/comments/{COMMENT_ID} |   - …
> [BE] Add new validations and improve comment update functionality

- android/app/src/androidTest/java/com/social/profileTest/UserProfileFragmentTest.kt
- android/app/src/main/java/com/social/presentation/profile/UserProfileFragment.kt
In this pull request I have improved the function that converts numbers in millions into M and thousands into K.
> [M] fix: Updating function convertNumberToK in UserProfileFragment

- .github/workflows/manual-terraform.yaml
This pull request introduces a new feature that establishes a Terraform pipeline to facilitate the deployment and management of infrastructure on Google Cloud Platform (GCP).
> [DEVOPS] Feat: setup terraform pipeline

- .github/workflows/manual-terraform.yaml
This pull request introduces a fix that establishes a Terraform pipeline to facilitate the deployment and management of infrastructure on Google Cloud Platform (GCP)
> [DEVOPS] fix: setup terraform pipeline

- QA/test_development/POST.postman_collection.json
**Endpoint:** https://31f26148-53be-474d-9a51-fa125946327a.mock.pstmn.io/create-post
**Method:** POST
**Body:**
```
{
"userId": 123,
"title": "Publicación con múltiples GIF",
"description": "Descripción de la publicación",
"hasMultimedia": true,
"public": true,
"multimedia": [
"gif1.gif",
"gif2.gif"
]
}
```
**Response**
```
{
"error": {
"code": "TOO_MANY_GIFS",
"message": "Solo se permite un GIF por publicación."
},
"status": "ERROR"
}
```
**Test**
```
pm.test("Validate response based on status", function () {
let response = pm.response.json();
if (response.status === "SUCCESS") {
pm.expect(response).to.have.property('response');
pm.expect(response.response).to.have.property('Id');
pm.expect(response.response).to.have.property('UserId'); …
```
> [QA] Test for post creation failed with Multiple GIFs

- QA/test_development/POST.postman_collection.json
**Fetching User Posts**
**Endpoint:** https://31f26148-53be-474d-9a51-fa125946327a.mock.pstmn.io/postsUser?userid=456
**Method:** GET
**Response**
```
{
"publications": [
{
"Id": 1,
"UserId": 456,
"Title": "Mi primera publicación",
"Description": "Esta es mi primera publicación en la plataforma.",
"HasMultimedia": false,
"Public": true,
"InsertionDate": "2023-11-07T10:00:00.000000000Z"
},
{
"Id": 2,
"UserId": 456,
"Title": "Otra publicación",
"Description": "Una segunda publicación para compartir contenido interesante.",
"HasMultimedia": true,
"Public": true,
"Multimedia": [
"imagen1.jpg",
"imagen2.jpg"
],
"InsertionDate": "2023-11-08T09:30:00.000000000Z"
}
]
}
```
**Fetching Posts without userId**
**Endpoint:** https://31f26148-53be-474d-9a51-fa125946327a.mock.pstmn.io/postsUser?userid= …
> [QA] Test for Fetching User Posts with UserID

- data/IaC/management_resource/resource_database/main.tf
- data/IaC/management_resource/resource_database/variables.tf
1. **Previous considerations**
- This Pull Request is the continuation of PR #876 and #888 (in that order).
2. **Task objective**
- This issue solves the task of creating the database, by infrastructure as code (IaC) using the Terraform tool.
3. **Requirements**
Tool Name | Definition
-- | --
Azure CLI v2.54.0  | Is a command-line tool that makes it easy to interact with Microsoft Azure services and resources.
Terraform v1.6.4 | They are an essential organizational tool that helps users manage and keep their resources organized.
4. Proccess
> We go to \data\IaC\management_resource, and create the folder, main.tf file and add lines of code to create the database resource and follow the following steps.
5. Conclusions
- This PR is based on previous work done on pull requests #876 and #888 …
> [DATA] Database resource, creation from Terraform
